name: Conditional Jobs

on:
  push:
    paths:
      - 'home/**'
    branches:
      - main
  workflow_dispatch:
    
jobs:
  job_for_dir1:
    runs-on: ubuntu-latest
    if: contains(github.event.commits.*.modified, 'home/') || contains(github.event.commits.*.added, 'home/') || contains(github.event.commits.*.removed, 'home/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and Deploy
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          APP_DIRECTORY: "./home"