name: Conditional Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  job_for_dir1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if Home changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-home
        with:
          paths: home
  
      - name: Update Home
        if: steps.changed-home.outputs.changed == 'true'      
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          APP_DIRECTORY: "./home"

      - name: Check if Github changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-github
        with:
          paths: .github
  
      - name: Update Github
        if: steps.changed-github.outputs.changed == 'true'      
        shell: bash
        run: |
          echo "github changed"
