name: Conditional Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

          
          

      - name: Check if Home changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-home
        with:
          paths: home
  
      - name: Update Home
        if: steps.changed-home.outputs.changed == 'true'
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          APP_DIRECTORY: "./home"
          
          
          

      - name: Check if Phyllotaxis changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-phy
        with:
          paths: phyllotaxis

      - name: Update Phyllotaxis
        if: steps.changed-phy.outputs.changed == 'true'      
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          TARGET_DIRECTORY: "./algorithm/phyllotaxis"
          APP_DIRECTORY: "./phyllotaxis"
          
          
          

      - name: Check if Maze changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-maze
        with:
          paths: maze
  
      - name: Update Maze
        if: steps.changed-maze.outputs.changed == 'true'      
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          TARGET_DIRECTORY: "./algorithm/maze"
          APP_DIRECTORY: "./maze"

          

          

      - name: Check if Pthfind changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-astar
        with:
          paths: aStar
  
      - name: Update A*
        if: steps.changed-astar.outputs.changed == 'true'      
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          TARGET_DIRECTORY: "./algorithm/aStar"
          APP_DIRECTORY: "./aStar"
          

          
          
          
      - name: Check if Combinations changed
        uses: marceloprado/has-changed-path@v1.0.1
        id: changed-comb
        with:
          paths: combination
  
      - name: Update Combinations
        if: steps.changed-comb.outputs.changed == 'true'      
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          TARGET_DIRECTORY: "./algorithm/combinotorics"
          APP_DIRECTORY: "./combinations"
