name: Conditional Jobs

on:
  push:
    paths:
      - 'home/**'
    branches:
      - main
  workflow_dispatch:
    
jobs:
  job_for_dir1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-front
        with:
          paths: home
  
      - name: Deploy front
        if: steps.changed-front.outputs.changed == 'true'      
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.ACT_TOK }}
          APP_DIRECTORY: "./home"