name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DIR_CHANGED: ${{ github.event.head_commit.modified }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set directory variable
      shell: bash
      run: |
        if [[ "${{ env.DIR_CHANGED }}" == *"home/"* ]]; then
          echo "dir='.'" >> $GITHUB_ENV
          echo "app='./home'" >> $GITHUB_ENV
        fi
        echo ${{ env.app }}
        echo ${{ env.dir }}
    # - name: Build and Deploy
    #   uses: mmedoo/build-react-on-push@v1.2
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     APP_DIRECTORY: ${{ env.app }}
    #     TARGET_DIRECTORY: ${{ env.dir }}