name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DIR_CHANGED: ${{ github.event.head_commit.modified }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set directory variable
      id: setdir
      run: |
        if [ "${{ env.DIR_CHANGED }}" == *"home/"* ]; then
          echo "dir=." >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build and Deploy for Subdirectory 1
      uses: mmedoo/build-react-on-push@v1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIRECTORY: "${{env.dir}}"
